version: 2.1

orbs:
  rebar3: tsloughter/rebar3@0.5.4

jobs:
  codecov:
    executor: rebar3/erlang
    steps:
      - rebar3/install_ca_certs
      - checkout
      - attach_workspace:
          at: ~/project/
      - run:
          command: |
            rebar3 covertool generate
            apk add --update python python-dev py-pip git
            pip install codecov && codecov -f _build/test/covertool/grpcbox.covertool.xml

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - rebar3/compile
      - rebar3/xref:
          requires:
            - rebar3/compile
      - rebar3/dialyzer:
          requires:
            - rebar3/compile
      - rebar3/ct:
          requires:
            - rebar3/compile
      - rebar3/cover:
          requires:
            - rebar3/ct
      - codecov:
          requires:
            - rebar3/cover
